### ISSUE TITLE
Error en cambiar contraseña

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#44]
## Proceso

1. Ir al login
2. Recuperar contraseña

## Resultado esperado

Recibir un formulario para restablecer la contraseña o en su defecto redirigir a página de error.

## Resultado actual

Al dar click en recuperar contraseña, esta redirige a inicio.

## Captura

<img width="814" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/20a70688-f73c-4ec4-a891-aea5d5cebf0f">

<img width="820" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/2cb20976-6f68-4d5b-ae7e-d5158baf5617">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Flujo Adverso del Evento
Al dar clic en recuperar contraseña, esta redirige a inicio.
### Corrección del Flujo Adverso
 Al dar clic en recuperar contraseña, redirige a Pagina de Error

**Comment by castromaciel** [comment]
Se valida la corrección
