### ISSUE TITLE
Espaciados en general

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#45]
## Proceso

1. Abrir la pagina web

## Resultado esperado

Los contenedores, deberían tener un espaciado hacia los costados como hacia arriba y hacia abajo. 
Adicional, las cards presentadas en el inicio también deberían tener espaciados.

## Resultado actual

Párrafos, cards e imágenes sin espacios entre sí

## Captura

<img width="1440" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/61d75b3a-e214-4577-92a2-6a7060a45eac">

![image](https://github.com/juanjobazan/prueba_Hotel/assets/83432755/22eef44c-a62a-498a-8e1c-b5d82cefc184)

![image](https://github.com/juanjobazan/prueba_Hotel/assets/83432755/f4701b14-11e5-43b3-84fe-3aec54dcb2bf)

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Flujo Adverso del Evento
Párrafos, cards e imágenes sin espacios entre sí
### Corrección
Se incorpora en los contenedores espacios en todos los sentidos. También se establece espacio entre las cards de Habitaciones y servicios.

**Comment by castromaciel** [comment]
Se valida la corrección
