### ISSUE TITLE
Error texto alternativo

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#46]
## Proceso

1. Ir al inicio.
2. Ver las cards presentadas

## Resultado esperado

En la grilla de habitaciones, las cards no tienen un texto alternativo.

## Resultado actual

No muestra texto alternativo.

## Captura

<img width="1440" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/6ad855a3-8b67-4af9-95dd-6f4919431bce">

<img width="1375" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/956de390-b958-46b3-9bf4-24109a894238">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Flujo Adverso
No se muestra texto alternativo.

### Corrección del Flujo Adverso

Se incorpora Texto Alternativo en las Cards de habitaciones "Alt", la misma contiene información del numero de habitación

**Comment by castromaciel** [comment]
Se valida el texto alternativo:
<img width="751" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/1be4b4a9-dd7b-496a-ae6a-5cd50ff9a1df">
