### ISSUE TITLE
Logo en el footer

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#47]
## Proceso

1. Navegar hacia el footer
2. Dar click en el logo

## Resultado esperado

Al presionar el logo en el footer debería llevar al usuario al inicio de la web.

## Resultado actual

No realiza ninguna acción. (Debería redirigir al inicio)

## Captura

<img width="1440" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/d7035cb9-b12a-4f12-99bd-8f96a4beb09a">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Flujo Adverso

No realiza ninguna acción. (Debería redirigir al inicio)

### Corrección del Flujo Adverso

En el logo del sitio establecido en el Footer de la pagina, se incorpora una redirección a la pagina inicio Home-Page del sitio. 
Al navegar sobre el mismo se puede apreciar lo implementado.

**Comment by castromaciel** [comment]
Se valida la corrección
