### ISSUE TITLE
Reservas

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#48]
## Proceso

1. Iniciar sesión
2. Mis reservas
3. Cerrar sesión

## Resultado esperado

Al cerrar sesión estando en la sección de mis reservas debería redirigir al usuario al inicio de la web.

## Resultado actual

Cerrando sesión permanece la sección de "mis reservas"

## Captura

<img width="814" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/0e7de44d-8540-46e5-b1a2-c7f968a50dfe">

<img width="814" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/0b2b2c5a-c72c-4966-992a-6bad19e3da2c">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Flujo Adverso

Cerrando sesión permanece la sección de "mis reservas"

### Corrección del Flujo Adverso

Al cerrar sesión ya sea user o admin, esto redirige al Home del sitio respetando un tiempo predefinido.

**Comment by castromaciel** [comment]
Se valida la corrección
