### ISSUE TITLE
Error en el registro

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#49]
## Proceso

1. Ir al registro
2. Diligenciar los campos del formulario
3. Dar click en el boton registrarse

## Resultado esperado

Al registrar un nuevo usuario, se espera un modal informando la creacion del mismo.

## Resultado actual

Muestra un error de no creación. pero el servicio responde de manera exitosa.

## Captura

<img width="1439" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/de757748-cb73-4d55-8d25-dd1f10456bfb">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Flujo Adverso del Evento

Muestra un error de no creación. pero el servicio responde de manera exitosa.

### Posible Solución del Flujo adverso

Al Crear un nuevo usuario, este si pasa por las validaciones predispuestas, se genera un nuevo usuario. Por su parte el sistema muestra un mensaje de Creacion Exitosa e invita al usuario a iniciar Sesión

**Comment by castromaciel** [comment]
En conjunto con el issue #53 

Se valida la solución
<img width="1138" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/91fb88af-9b5c-40b6-ad1a-dc5639afe9cb">
