### ISSUE TITLE
Botón pagar

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#50]
## Proceso

1. Iniciar sesión
2. Ir a reservas
3. Pagar

## Resultado esperado

Recibir un formulario para realizar el pago o redirigir a la página de error.

## Resultado actual

Al dar click en el botón pagar, no realiza ninguna acción.

## Captura

<img width="1438" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/6e845021-85cd-461c-a2cf-7a2a6102ad35">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Flujo Adverso del Evento

Al dar clic en el botón pagar, no realiza ninguna acción.

### Corrección del Caso Adverso

El usuario al dar clic en botón Pagar, el sistema redirige a pagina error

**Comment by castromaciel** [comment]
Se valida la corrección 

<img width="635" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/2cb6ede2-5d9a-4cc7-a0c1-a92c8ed82071">
