### ISSUE TITLE
Placeholder Editar habitación

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#51]
## Proceso

1. Iniciar sesión con usuario admin
2. Editar las habitaciones creadas

## Resultado esperado

Al editar/modificar una habitacion, se espera que al usuario se le presente el formulario con los labels e inputs correspondientes. 

## Resultado actual

El formulario de edición tiene el mismo placeholder para todos los campos

## Captura

<img width="569" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/91f8b70d-1fad-43e3-99dc-faa9b97c397c">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Caso Adverso del Evento

El formulario de edición tiene el mismo marcador de posición para todos los campos.

### Corrección del Evento

Corrección en los inputs, mostrando al usuario lo necesario para facilitar el manejo del sistema

**Comment by castromaciel** [comment]
Se valida la solución


<img width="635" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/fb4e07a7-6ad2-434c-baee-576acb57fab7">
