### ISSUE TITLE
ID's en general

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#52]
## Proceso

1. Iniciar sesión como admin
2. Inspeccionar los elementos del formulario "Editar habitación"
3. Inspeccionar los elementos del formulario "Alta de servicios"

## Resultado esperado

Al ver los elementos de la pagina, se espera que cada elemento tenga un id único.

## Resultado actual

Todos los inputs tienen el mismo id. Recordemos, que el id es un identificador unico de cada elemento html. Por que el mismo no debería estar duplicado.

## Captura

<img width="1440" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/1b2aed06-2cb2-4cf3-bbef-24098472429f">

<img width="1191" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/4b3317c7-58c1-4a66-8452-98aaa5e0181c">

<img width="1233" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/5a7717a1-e6a0-4e43-93ed-833378a97c0a">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Casos Adversos

Todos los inputs tienen el mismo id. Recordemos que el id es un identificador único de cada elemento html. Por que el mismo no debería estar duplicado.

### Corrección de los eventos

Se modifica todos los ID de cada elemento HTML, ya que estos deben ser únicos.

**Comment by castromaciel** [comment]
Se valida la corrección

<img width="1026" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/66f77c69-b640-424d-863d-e4bb351fe872">
