### ISSUE TITLE
Creación usuarios

### ISSUE THREAD

**Issue by castromaciel** [juanjobazan/prueba_Hotel#53]
## Proceso

1. Ir al registro de Usuario.
2. Diligenciar el formulario
3. Registrar el usuario
4. Cambiar el nombre de usuario
5. Volver a registrar con el mismo correo

## Resultado esperado

A la hora de crear usuarios, tanto el nombre de usuario, como correo electronico deberían ser únicos para cada usuario.

## Resultado actual

Permite la creación de usuarios con el mismo correo

## Captura

<img width="750" alt="image" src="https://github.com/juanjobazan/prueba_Hotel/assets/83432755/d901b86a-7936-4ac1-8286-b8c268cf030d">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by juanjobazan** [comment]
### Caso Adverso del Evento

Permite la creación de usuarios con el mismo correo

### Solución del Evento

Se agrega otro requerimiento al Back, en el cual el tipo: email, debe ser único en el sistema, es decir que un usuario además de no poder utilizar un usuario ya registrado, No puede utilizar un  email registrado.
